//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataToBim.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataToBim.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature
        ///31
        ///8234.21509366
        ///3574326.0,10179650.0833,3574326.5,10179637.25,3574342.83325,10179637.9167,3574343.66675,10179618.4167,3574337.5,10179618.0833,3574338.5,10179594.8333,3574347.91675,10179595.25,3574348.75,10179576.1667,3574338.41675,10179575.75,3574339.0,10179562.1667,3574330.25,10179561.75,3574330.41675,10179558.3333,3574325.91675,10179558.1667,3574326.08325,10179554.0833,3574314.25,10179553.5833,3574314.0,10179558.5833,3574309.83325,10179558.4167,3574308.66675,10179586.25,3574284.58325,10179585. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Buildings {
            get {
                return ResourceManager.GetString("Buildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature
        ///3554540.37525,10211924.9638,314.0,3554542.2195,10211927.808,314.0,3554544.29225,10211929.751,314.0,3554546.51325,10211931.1018,314.0,3554551.40875,10211935.5387,314.0,3554553.932,10211938.1695,314.0,3554555.5555,10211940.5825,314.0,3554560.94375,10211945.372,314.0,3554563.625,10211947.9038,314.0,3554565.716,10211951.2697,314.0,3554568.10375,10211958.0483,314.0,3554565.34525,10211962.226,314.0,3554564.324,10211962.801,314.0,3554557.2545,10211964.9698,314.0,3554551.9045,10211965.862,314.0,3554546.914 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Contour {
            get {
                return ResourceManager.GetString("Contour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature
        ///3552709.85708,10211126.218,3552626.21186,10211054.2646,3552553.77314,10210992.1374,3552553.20557,10210991.5564,3552552.9387,10210991.0876,3552552.74156,10210990.2984,3552552.86271,10210989.2319,3552553.09333,10210988.7353,3552553.41537,10210988.3076,3552554.05507,10210987.7991,3552554.46467,10210987.6237,3552555.62336,10210987.5357,3552556.77838,10210987.5786,3552557.92646,10210987.7425,3552559.05128,10210988.0242,3552560.14629,10210988.4171,3552561.18202,10210988.9308,3552562.16836,10210989.5425,3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Roads {
            get {
                return ResourceManager.GetString("Roads", resourceCulture);
            }
        }
    }
}
